# Generated by Django 3.2.6 on 2021-08-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
