# Generated by Django 3.2.6 on 2021-08-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase_translation', models.ManyToManyField(related_name='category', to='language_app.Korean')),
            ],
        ),
    ]
