# Generated by Django 3.2.6 on 2021-08-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_app', '0005_rename_foreign_phrase_korean_korean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
